### ISSUE TITLE
Panic when single block used to generate tree.

### ISSUE THREAD

**Issue by euforia** [xsleonard/go-merkle#2]
When trying to generate a tree with a single block it panics.  Here's how to reproduce:

```
func TestTreeGenerate_1(t *testing.T) {
    tree := NewTree()
    blocks := [][]byte{[]byte("foo")}
    if err := tree.Generate(blocks, NewSimpleHash()); err != nil {
        t.Fatal(err)
    }
}
```

Am I missing something here?  Thanks in advance.

**Comment by euforia** [comment]
Here's the panic:
```
	/Users/abs/.gvm/gos/go1.6.3/src/runtime/panic.go:443 +0x4e9
github.com/xsleonard/go-merkle.(*Tree).generateNodeLevel(0xc820059ef0, 0xc820015200, 0x1, 0x1, 0xc820015200, 0x0, 0x0, 0x14048f8, 0x5e8e88, 0x0, ...)
	github.com/xsleonard/go-merkle/_test/_obj_test/merkle.go:234 +0x394
github.com/xsleonard/go-merkle.(*Tree).Generate(0xc820059ef0, 0xc820059e90, 0x1, 0x1, 0x14048f8, 0x5e8e88, 0x0, 0x0)
	github.com/xsleonard/go-merkle/_test/_obj_test/merkle.go:174 +0x6f3
github.com/xsleonard/go-merkle.TestTreeGenerate_1(0xc82008a750)
	/Users/abs/workbench/golang/src/github.com/xsleonard/go-merkle/merkle_test.go:450 +0x220
testing.tRunner(0xc82008a750, 0x5c9328)
	/Users/abs/.gvm/gos/go1.6.3/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/Users/abs/.gvm/gos/go1.6.3/src/testing/testing.go:582 +0x892
exit status 2
FAIL	github.com/xsleonard/go-merkle	0.013s
```

**Comment by lucasvo** [comment]
@euforia Is there a reason you want to create a tree with a single block? The way `go-merkle` is implemented, if the last branch has just one leaf, the parent of the leaf is actually not the hash of just the last leaf but it just copies that hash. 

Therefore while a tree with two nodes makes sense, one with just one would be awkward:

```
     H(A,B)        A
     /   \         |
    A     B        A
```

Implementing it would essentially just mean that tree.Root() is the hash of the first leaf. Is there any scenario where you'd want that?

**Comment by lucasvo** [comment]
PS: It looks like #1 is also about the same topic...

**Comment by euforia** [comment]
@lucasvo - You're right. It makes more sense to treat a single item as a special case as if defeats the purpose of the tree. :)  I came to the same conclusion and forgot to close the issue, though I  appreciate you responding.
